In [1]:
import pandas as pd

In [50]:
# Cleaning Data
# Handling missing value

df = pd.read_csv("raw_data.csv")
df.isnull()
df.isna() # alies name for isnull()
df.isnull().sum() # chaning function
df.dropna() # drop row which has null value
df.dropna(axis = 1) # drop column
df.fillna(0)

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

df.ffill()
df.bfill()

,id,name,age,department,salary,joining_date,email
0,1,John Doe,29.0,Sales,50000,2021-05-10,john.doe@email.com
1,2,Jane Smith,30.0,HR,45000,10/06/2020,jane.smith@email.com
2,3,Mike Johnson,30.0,IT,60000,2022-01-15,mike.j@email
3,4,Emily Davis,34.0,Finance,52000,2021/07/20,emily.davis@email.com
4,5,Chris Brown,28.0,Sales,52000,15-08-2021,chris.brown@email.com
5,6,Sarah Wilson,42.0,HR,48000,2020-11-30,sarah.wilson@email.com
6,7,David Lee,42.0,IT,not_available,2019-03-25,david.lee@email.com
7,8,Anna Kim,31.0,Finance,61000,2022-13-01,anna.kim@email.com
8,9,John Doe,29.0,Sales,50000,2021-05-10,john.doe@email.com
9,10,Mark Taylor,27.0,IT,58000,2021-09-31,mark.taylor@email.com
10,11,Lisa White,33.0,HR,47000,2020-02-29,lisa.white@email.com
11,12,Tom Clark,45.0,Finance,65000,2020-02-29,tom.clark@email.com
12,13,Nina Patel,29.0,Sales,53000,2021-04-12,nina.patel@email.com
13,14,Raj Mehta,35.0,IT,62000,2021-06-18,raj.mehta@email.com
14,15,Amit Sharma,35.0,Finance,67000,2021-07-25,amit.sharma@email

In [74]:
# handling Dupliction value
df["joining_date"].duplicated()
df[["department","joining_date"]].duplicated()
dfc = df.copy()
# df[["department","joining_date"]].drop_duplicates(inplace = True)

C:\Users\kashi\AppData\Local\Temp\ipykernel_17020\1667976515.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["department","joining_date"]].drop_duplicates(inplace = True)

In [99]:
# handling data types
df.dtypes
df["age"] = df["age"].fillna(0)
df["age"] = df["age"].astype("int64")
df.dtypes
df["joining_date"] = pd.to_datetime(df["joining_date"] , format="mixed", dayfirst=True, errors="coerce")
df["name"] = df["name"].astype("string")
df.dtypes

id                       int64
name            string[python]
age                      int64
department              object
salary                  object
joining_date    datetime64[ns]
email                   object
dtype: object

In [107]:
# handling string
df["name"].str.upper()
df["name"].str.lower()
df["name"].str.capitalize()
df["name"].str.split(" ")
df["name"].str.contains("J" , case = False)

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13     True
14    False
Name: name, dtype: boolean

In [96]:
df

,id,name,age,department,salary,joining_date,email
0,1,John Doe,29,Sales,50000,2021-05-10,john.doe@email.com
1,2,Jane Smith,0,HR,45000,2020-06-10,jane.smith@email.com
2,3,Mike Johnson,30,IT,60000,2022-01-15,mike.j@email
3,4,Emily Davis,34,Finance,NaN,2021-07-20,emily.davis@email.com
4,5,Chris Brown,28,Sales,52000,2021-08-15,chris.brown@email.com
5,6,Sarah Wilson,0,HR,48000,2020-11-30,sarah.wilson@email.com
6,7,David Lee,42,IT,not_available,2019-03-25,david.lee@email.com
7,8,Anna Kim,31,Finance,61000,2022-01-13,anna.kim@email.com
8,9,John Doe,29,Sales,50000,2021-05-10,john.doe@email.com
9,10,Mark Taylor,27,IT,58000,NaT,mark.taylor@email.com
10,11,Lisa White,33,HR,47000,NaT,lisa.white@email.com
11,12,Tom Clark,45,Finance,65000,2020-02-29,tom.clark@email.com
12,13,Nina Patel,29,Sales,53000,2021-04-12,nina.patel@email.com
13,14,Raj Mehta,0,IT,62000,2021-06-18,raj.mehta@email.com
14,15,Amit Sharma,35,Finance,67000,2021-07-25,amit.sharma@email