In [21]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

,id,name,age,department,salary,joining_date,email
0,1,John Doe,29.0,Sales,50000,2021-05-10,john.doe@email.com
1,2,Jane Smith,NaN,HR,45000,10/06/2020,jane.smith@email.com
2,3,Mike Johnson,30.0,IT,60000,2022-01-15,mike.j@email
3,4,Emily Davis,34.0,Finance,NaN,2021/07/20,emily.davis@email.com
4,5,Chris Brown,28.0,Sales,52000,15-08-2021,chris.brown@email.com
5,6,Sarah Wilson,NaN,HR,48000,2020-11-30,sarah.wilson@email.com
6,7,David Lee,42.0,IT,not_available,2019-03-25,david.lee@email.com
7,8,Anna Kim,31.0,Finance,61000,2022-13-01,anna.kim@email.com
8,9,John Doe,29.0,Sales,50000,2021-05-10,john.doe@email.com
9,10,Mark Taylor,27.0,IT,58000,2021-09-31,mark.taylor@email.com
10,11,Lisa White,33.0,HR,47000,NaN,lisa.white@email.com
11,12,Tom Clark,45.0,Finance,65000,2020-02-29,tom.clark@email.com
12,13,Nina Patel,29.0,Sales,53000,2021-04-12,nina.patel@email.com
13,14,Raj Mehta,NaN,IT,62000,2021-06-18,raj.mehta@email.com
14,15,Amit Sharma,35.0,Finance,67000,2021-07-25,amit.sharma@email

In [91]:
# Transformation on data
df2 = df.copy()
df2["salary"] = df2["salary"].fillna(0)
df2.loc[6,"salary"] = 40000
df2["salary"] = df2["salary"].astype("float64")

# apply()
# adding new column and tax if the salary above 50k

df2["tax"] = df2["salary"].apply(lambda x : "20%" if x >= 50000 else "10%")
df2

# map()
department_map = {"Sales":"S","HR":"H","IT":"I","Finance":"F"}
df2["department"] = df2["department"].map(department_map)
df2

# assing()
df2 = df2.assign(new_salary_with_30_percent_hike = df2["salary"] * 1.3)

# replace()
df2["name"] = df2["name"].replace("John Doe","Kashi")
df2

# Rename
df2.columns = ["Id","Name","Age","Department","Salary","Joining_Date","Email","Tax","New_Salary_With_30_Percent_Hike"]
df2 = df2.rename(columns={"New_Salary_With_30_Percent_Hike":"New_Salary"})
df2 = df2.rename(index={1:"First"})
df2

# Sort
df2["Salary"].sort_values()
df2 = df2.sort_values(by="Salary", ascending=False)

#reset
df2 = df2.reset_index()
df2 = df2.reset_index(drop = True)

# ranking
df2["Ranking"] = df2["Salary"].rank()
df2["Ranking"] = df2["Salary"].rank(method = "dense") # to resolve tia same vale
df2["Ranking"] = df2["Salary"].rank(method = "min")
df2["Ranking"] = df2["Salary"].rank(method = "max")
df2

# re-ordring colunms named
df2 = df2[["Id","Name","Age","Department","Salary","Joining_Date","Email","New_Salary" ,"Tax",]]
df2

,Id,Name,Age,Department,Salary,Joining_Date,Email,New_Salary,Tax
0,15,Amit Sharma,35.0,F,67000.0,2021-07-25,amit.sharma@email,87100.0,20%
1,12,Tom Clark,45.0,F,65000.0,2020-02-29,tom.clark@email.com,84500.0,20%
2,14,Raj Mehta,NaN,I,62000.0,2021-06-18,raj.mehta@email.com,80600.0,20%
3,8,Anna Kim,31.0,F,61000.0,2022-13-01,anna.kim@email.com,79300.0,20%
4,3,Mike Johnson,30.0,I,60000.0,2022-01-15,mike.j@email,78000.0,20%
5,10,Mark Taylor,27.0,I,58000.0,2021-09-31,mark.taylor@email.com,75400.0,20%
6,13,Nina Patel,29.0,S,53000.0,2021-04-12,nina.patel@email.com,68900.0,20%
7,5,Chris Brown,28.0,S,52000.0,15-08-2021,chris.brown@email.com,67600.0,20%
8,1,Kashi,29.0,S,50000.0,2021-05-10,john.doe@email.com,65000.0,20%
9,9,Kashi,29.0,S,50000.0,2021-05-10,john.doe@email.com,65000.0,20%
10,6,Sarah Wilson,NaN,H,48000.0,2020-11-30,sarah.wilson@email.com,62400.0,10%
11,11,Lisa White,33.0,H,47000.0,NaN,lisa.white@email.com,61100.0,10%
12,2,Jane Smith,NaN,H,45000.0,10/06/2020,jane.smith@email.com,58500.0,10%
13,7,David Lee,42.0,I,40000.0,2019-03-25,david.lee@email.com,52000.0,10%
14,4,Emily Davis,34.0,F,0.0,2021/07/20,emily.davis@email.com,0.0,10%